theme: jekyll-theme-cayman
title: Frocole
description: Frocole Documentation

url: "https://frocole.github.io/"
permalink: /:title/

# Plugins
plugins:
  - jekyll-multiple-languages-plugin
#  - jekyll-paginate
#  - jekyll-sitemap
# - jekyll-include-cache

# jekyll-multiple-languages-plugin settings:
languages: ["en", "nl"]
exclude_from_localizations: ["javascript", "images", "css", "scripts", "favicon.ico"]
defaultLang: nl
languageNames:
  nl: Dutch
  en: English
default_locale_in_subfolder: true
